#!/bin/bash
# -*- sh -*-

: << =cut

=head1 NAME

WP_versioncheck - finds installed wordPress and display version info.

=head1 CONFIGURATION

This plugin does not normally require configuration.
run as root.

=head1 AUTHOR

Original author ka7

Copyright (C) 2017 ka7 <ka7@la-evento.com>

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf suggest

=cut

#. "${MUNIN_LIBDIR}/plugins/plugin.sh"
. /usr/share/munin/plugins/plugin.sh 

# loop over all the installed versions, fetch installed version-numbers
write_versions(){
  for FILE in $(locate wp-includes/version.php)
  do
    VERSTR=$(grep "\$wp_version" "$FILE" | sed 's/[^0-9.]*//g'| sed '/^$/d' | awk -F'.' '{print $1*10000 + $2*100 + $3*1}')
    WP_I2=$( echo "$FILE" | sed 's/wp-includes\/version.php//g' )
    WP_I="$(clean_fieldname \"$WP_I2\")";
  #  WP_I=$( ${FILE//wp-includes\/version.php/} ) # mightwork
#    WP_V=$( echo "$VERSTR"  )  

    echo "$WP_I.value $VERSTR";
  done
}

# detect the up-to-date lastest stable of WP, e.g via uscan
detect_latest_stable(){
#  CACHEDIR="/var/lib/munin-node/plugin-state/root";
  CACHEDIR="/tmp";
  CACHEFILE="$CACHEDIR/wp_latest_version.txt";
  CMIN=720; # default to 12 hours. maybe as env-option ?

  if [ ! -d "$CACHEDIR" ];
  then
    mkdir -p "$CACHEDIR"; # just in case ?
  fi

  if [ ! -f "$CACHEFILE" ];
  then
    # file does not exists; create.
    WP_LATEST=$( wget --server-response --spider -q -O - "https://wordpress.org/latest" 2>&1 \
            | grep "Content-Disposition:" | tail -1  \
            | awk 'match($0, /filename=(.+)/, f){ print f[1];}' \
            | sed 's/[^0-9.]*//g'| awk -F'.' '{print $1*10000 + $2*100 + $3*1}')
    umask 077; # make file "secure"
    echo "$WP_LATEST" > "$CACHEFILE";
  else
    WP_LATEST=$(cat "$CACHEFILE"); 
  fi

  # file too old, clear so it gets refreshed.
  echo find -cmin "$CMIN" -wholename "$CACHEFILE" -type f -delete
}

case $1 in
    autoconf)
        if [ $(locate "wp-includes/version.php" | wc -l ) -gt 0 ]; then
            echo yes
            exit 0
        else
            echo "no WP-installations found"
            exit 0
        fi
        ;;
    suggest)

        exit 0
        ;;
    config)

        echo -n "graph_order "
        for FILE in $(locate wp-includes/version.php)
        do
          lab2=$( echo "$FILE" | sed 's/wp-includes\/version.php//g' )
          lab="$(clean_fieldname \"$lab2\")";
          echo -n " $lab"
        done
        echo ""

        echo "graph_title WordPress version"
        echo 'graph_args --base 1000'
        echo 'graph_vlabel version (1.2.3 = 010203 )'
        echo 'graph_category system'
        echo "graph_info search for active WP installations (by locate wp-includes/version.php), grep the version, interprete."

        detect_latest_stable;

        for FILE in $(locate "wp-includes/version.php")
        do
          lab2=$( echo "$FILE" | sed 's/wp-includes\/version.php//g' )
          lab="$(clean_fieldname \"$lab2\")";
          echo "$lab.label $lab2"
          echo "$lab.type GAUGE"
          echo "$lab.units-exponent 0"
          echo "$lab.warning $WP_LATEST"
        done

#        print_warning WPversion
#        print_critical WPversion
         exit 0
         ;;
esac

        write_versions;


